version: '3'
services:
  web:
    build: .
    command: bundle exec rails s -p 3001 -b '0.0.0.0'
    volumes:
      - .:/finance-app
    ports:
      - "3001:3001"
    depends_on:
      - sidekiq
    environment:
      - REDIS_URL_SIDEKIQ=redis://redis:6379/1
    tty: true
    stdin_open: true

  redis:
    image: 'redis:6-alpine'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'

  sidekiq:
    depends_on:
      - 'redis'
    build: .
    command: bundle exec sidekiq
    volumes:
      - '.:/finance-app'
      - '/finance-app/tmp' # don't mount tmp directory
    environment:
      - REDIS_URL_SIDEKIQ=redis://redis:6379/1

volumes:
  redis: